Periodic kernel handles multi-dimensional inputs
cornellius-gp/gpytorch pull request #1593
Opened 2021-04-26 23:09 UTC by tawe141

Periodic kernel now uses eq. 47 in David Mackay's Introduction to Gaussian Processes, found here: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.81.1927&rep=rep1&type=pdf

with one small difference: it doesn't do different period lengths or lengthscales for each feature. Fixes #835 

If I were to add in ARD, would this be a different PR or can I add it here? Sorry, new to this whole contributing to open source thing, so let me know what works best for everyone. Thanks for your patience :)

2021-05-03 23:12 UTC, gpleiss requested changes
Hey @tawe141 sorry for the slow review! Thanks for the contribution - just a few small changes and then we can merge :)

2021-05-03 23:12 UTC, gpleiss commented on gpytorch/kernels/periodic_kernel.py
> +        if x1.dim() == 3 and x2.dim() == 3:  # batched operation
This code will fail if you have a multi-batch GP (4 or more tensor dimensions). It's better to do `diff = x1.unsqueeze(-2) - x2.unsqueeze(-3)`.

2021-05-03 23:12 UTC, gpleiss commented on gpytorch/kernels/periodic_kernel.py
> +        diff = diff * math.pi / self.period_length.unsqueeze(-1)
I've found that things tend to be more mathematically stable when you divide by the period length before you compute the difference. Can we go back to using L110-111?

2021-05-04 00:07 UTC, gpleiss approved these changes

2021-05-31 12:08 UTC, jacobrgardner commented
Also Fixes #1615

2021-05-31 12:11 UTC, merged